# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  clean:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.9

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run clean!
      - run:
          name: Clean
          command: mvn clean
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.9

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run tests!
      - run:
          name: Test
          command: mvn integration-test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  clean_build:
    jobs:
      - clean
      - build:
          requires:
            - clean
